# This file defines all the external services required
# to run the application in development mode.

volumes:
  pgdata:
    name: ${POSTGRES_VOLUME_NAME:-pgdata}
    driver: local

services:
  db:
    image: postgres:${POSTGRES_VERSION:-17-alpine}
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - ${POSTGRES_VOLUME_NAME:-pgdata}:/var/lib/postgresql/data

