name: Main CD Pipeline

on:
  push:
    branches: [trunk]

env:
  REGISTRY: ${{ vars.REGISTRY }}
  IMAGE_NAME: ${{ github.repository }}

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [web]
    steps:
      - uses: actions/checkout@v4

      - name: Set up project tools
        uses: jdx/mise-action@v2
        with:
          install: true
          cache: true

      - name: Build docker images
        run: |
          docker build -t $REGISTRY/$IMAGE_NAME:${{ matrix.app }} -f apps/${{ matrix.app }}/Dockerfile

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push docker images
        run: |
          docker push $REGISTRY/$IMAGE_NAME:${{ matrix.app }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        run: echo "Deploy step goes here"
