name: Sekrets CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Codebase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/workflows/setup-tools.yml
        with:
          go-version: ${{ vars.GO_VERSION }}
          golangci-lint-version: ${{ vars.GOLANGCI_LINT_VERSION }}
          node-version: ${{ vars.NODE_VERSION }}
          pnpm-version: ${{ vars.PNPM_VERSION }}
          turbo-version: ${{ vars.TURBO_VERSION }}

      - name: Run Linting
        run: turbo run lint

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/workflows/setup-tools.yml
        with:
          go-version: ${{ vars.GO_VERSION }}
          golangci-lint-version: 'none'
          node-version: ${{ vars.NODE_VERSION }}
          pnpm-version: ${{ vars.PNPM_VERSION }}
          turbo-version: ${{ vars.TURBO_VERSION }}

      - name: Run Tests
        run: turbo run test

  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/workflows/setup-tools.yml
        with:
          go-version: ${{ vars.GO_VERSION }}
          golangci-lint-version: 'none'
          node-version: ${{ vars.NODE_VERSION }}
          pnpm-version: ${{ vars.PNPM_VERSION }}
          turbo-version: ${{ vars.TURBO_VERSION }}

      - name: Build Application
        run: turbo run build

